---
Resources:
  EBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      InstanceType: t2.nano
      AvailabilityZone: us-east-1a
      ImageId: ami-80861296
    DeletionPolicy: Snapshot

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref EBSVolume
      VolumeId: !Ref NewVolume
      Device: /dev/sdh
