Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:      
      InstanceType: t2.nano
      ImageId: ami-80861296
      Volumes:
        -
          Device: "/dev/sdf"
          VolumeId: !Ref VolumeMount

  VolumeMount:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    Properties:
      AvailabilityZone: us-east-1a
      Size: 10
      VolumeType: gp2
